#!/bin/sh
###
# @file
# Shell script to be called by 'git-send-email --cc-cmd' to pick the correct
# maintainer emails for each patch when sending a series.
#
# Copyright (C) 2019, Red Hat, Inc.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# This script expects the following EDK2 environment variables defined:
# - WORKSPACE
# - EDK_TOOLS_PATH
#
###

set -e

#
# git-send-email calls this script with a list of patches generated by
# git-format-patch.
#
for arg in $@; do
    case ${arg} in
    *0000-cover-letter.patch)
        break
        ;;
    *.patch)
        test -e ${arg} && (
            cd ${WORKSPACE} && \
            head -1 < ${arg} \
            | cut -d' ' -f2 \
            | xargs python ${EDK_TOOLS_PATH}/Scripts/GetMaintainer.py --quiet
        )
        break
        ;;
    esac
done
